/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ann;

import java.io.File;
import java.util.Arrays;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import jxl.Sheet;
import jxl.Workbook;

/**
 *
 * @author USER
 */
public class P_AIS1 extends javax.swing.JPanel {

    /**
     * Creates new form P_AIS
     */
    public P_AIS1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("Jumlah Data = ");

        jButton2.setText("Random");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Set");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Proses");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("K = ");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel3.setText("T =");

        jTextField3.setText("27");

        jButton5.setText("Open File...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < jTable1.getRowCount(); i++) {

            for (int j = 0; j < jTable1.getRowCount(); j++) {
                //hasil = Math.abs(jTable1.getValueAt(i, 0).toString() - jTable1.getValueAt(j, 0).toString())
                float kurang_x1 = Math.abs(Float.parseFloat(jTable1.getValueAt(i, 0).toString()) - Float.parseFloat(jTable1.getValueAt(j, 0).toString()));
                float kurang_x2 = Math.abs(Float.parseFloat(jTable1.getValueAt(i, 1).toString()) - Float.parseFloat(jTable1.getValueAt(j, 1).toString()));
                float kurang_x3 = Math.abs(Float.parseFloat(jTable1.getValueAt(i, 2).toString()) - Float.parseFloat(jTable1.getValueAt(j, 2).toString()));
                float kurang_x4 = Math.abs(Float.parseFloat(jTable1.getValueAt(i, 3).toString()) - Float.parseFloat(jTable1.getValueAt(j, 3).toString()));
                float kurang_x5 = Math.abs(Float.parseFloat(jTable1.getValueAt(i, 4).toString()) - Float.parseFloat(jTable1.getValueAt(j, 4).toString()));
                float kurang_x6 = Math.abs(Float.parseFloat(jTable1.getValueAt(i, 5).toString()) - Float.parseFloat(jTable1.getValueAt(j, 5).toString()));
                float kurang_x7 = Math.abs(Float.parseFloat(jTable1.getValueAt(i, 6).toString()) - Float.parseFloat(jTable1.getValueAt(j, 6).toString()));
                float kurang_x8 = Math.abs(Float.parseFloat(jTable1.getValueAt(i, 7).toString()) - Float.parseFloat(jTable1.getValueAt(j, 7).toString()));
                float kurang_x9 = Math.abs(Float.parseFloat(jTable1.getValueAt(i, 8).toString()) - Float.parseFloat(jTable1.getValueAt(j, 8).toString()));
                float hasil = kurang_x1+kurang_x2+kurang_x3+kurang_x4+kurang_x5+kurang_x6+kurang_x7+kurang_x8+kurang_x9;
                jTable2.setValueAt(String.valueOf(hasil), i, j);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            // Random ran = new Random();
            int data1 = (int) (Math.random() * 10);
            int data2 = (int) (Math.random() * 10);
            int data3 = (int) (Math.random() * 10);
            int data4 = (int) (Math.random() * 10);
            int data5 = (int) (Math.random() * 10);
            int data6 = (int) (Math.random() * 10);
            int data7 = (int) (Math.random() * 10);
            int data8 = (int) (Math.random() * 10);
            int data9 = (int) (Math.random() * 10);
            jTable1.setValueAt(data1, i, 0);
            jTable1.setValueAt(data2, i, 1);
            jTable1.setValueAt(data2, i, 2);
            jTable1.setValueAt(data2, i, 3);
            jTable1.setValueAt(data2, i, 4);
            jTable1.setValueAt(data2, i, 5);
            jTable1.setValueAt(data2, i, 6);
            jTable1.setValueAt(data2, i, 7);
            jTable1.setValueAt(data2, i, 8);
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(jTextField1.getText());
        setttable1(jTable1, a);
        setttable(jTable2, a);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setttable3(jTable3, jTable1.getRowCount(), Integer.parseInt(jTextField2.getText()));

        for (int i = 0; i < jTable2.getRowCount(); i++) {
            float datatable[] = new float[jTable2.getRowCount()];
            for (int j = 0; j < jTable2.getRowCount(); j++) {
                if(j != i){
                    datatable[j] = Float.parseFloat(jTable2.getValueAt(i, j).toString());
                }else{
                    datatable[j] = 2000000000;
                }
            }
            Arrays.sort(datatable);
            for (int j = 0; j < Integer.parseInt(jTextField2.getText()); j++) {
                jTable3.setValueAt(datatable[j], i, j);
            }
        }

        for (int i = 0; i < jTable3.getRowCount(); i++) {
            double jumalah = 0;
            for (int j = 0; j < jTable3.getColumnCount()-2; j++) {
                jumalah = jumalah + Double.parseDouble(jTable3.getValueAt(i, j).toString());
            }
            double rata = jumalah / (jTable3.getColumnCount()-2);
            jTable3.setValueAt(String.valueOf(rata), i,Integer.parseInt(jTextField2.getText()));
        }

        int k = Integer.parseInt(jTextField2.getText());
        for (int i = 0; i < jTable3.getRowCount(); i++) {
            if(Double.parseDouble(jTable3.getValueAt(i, k).toString()) >= Double.parseDouble(jTextField3.getText())){
                jTable3.setValueAt("4 (malignant)", i, k+1);
            }else{
                jTable3.setValueAt("2 (benign)", i, k+1);
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Excel File", "xls"));

        int retval = chooser.showOpenDialog(null);
        if(retval == JFileChooser.APPROVE_OPTION){
            File f = chooser.getSelectedFile();
            filltable(f,jTable1);
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private void filltable(File excelfile, JTable table) {
        if(excelfile.exists()){
            try {
                Workbook workbook = Workbook.getWorkbook(excelfile);
                Sheet sheet = workbook.getSheet(0);
                //int jumlahrow = sheet.getRows();
                //int jumlahcolumn = sheet.getColumns();
                //untuk setting table
                
                for (int row = 0; row < table.getRowCount(); row++) {
                    for (int column = 0; column < table.getColumnCount(); column++) {
                        String isi = sheet.getCell(column, row).getContents();
                        table.setValueAt(isi, row, column);
                    }
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

    public void setttable(JTable table, int row){
            DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(    
              new Object [][] {
                    {}
                },
                new String [] {
                    
                }  
        );

        table.setModel(tableModel);
            String[] data= {null};

            for (int i=1; i<row; i++){
                ((DefaultTableModel)table.getModel()).addRow(data);
            }
                for (int i = 0; i < row; i++) {
                    ((DefaultTableModel)table.getModel()).addColumn(null);
                }
                ((DefaultTableModel)table.getModel()).addColumn("Lokasi");
               
                for (int i = 0; i < table.getRowCount(); i++) {
                    table.setValueAt(table.getColumnName(i), i, row);
                }
            
     }
    
    public void setttable1(JTable table, int row){
            DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(    
              new Object [][] {
                    {null,null,null,null,null,null,null,null,null}
                },
                new String [] {
                    "Clump Thickness","Uniformity of Cell Size","Uniformity of Cell Shape","Marginal Adhesion",
                    "Single Epithelial Cell Size","Bare Nuclei","Bland Chromatin","Normal Nucleoli","Mitoses"
                }  
        );

        table.setModel(tableModel);
            String[] data= {null,null,null,null,null,null,null,null,null};

            for (int i=1; i<row; i++){
                ((DefaultTableModel)table.getModel()).addRow(data);
            }
            
     }
    
    public void setttable3(JTable table, int row, int kolom){
            DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(    
              new Object [][] {
                    {}
                },
                new String [] {
                    
                }  
        );

        table.setModel(tableModel);
            String[] data= {null};

            for (int i=1; i<row; i++){
                ((DefaultTableModel)table.getModel()).addRow(data);
            }
                for (int i = 0; i < kolom; i++) {
                    ((DefaultTableModel)table.getModel()).addColumn(null);
                }
            ((DefaultTableModel)table.getModel()).addColumn("RJ");
            ((DefaultTableModel)table.getModel()).addColumn("Class");
     }

    
}
