/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ann;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.DecimalFormat;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import jxl.Sheet;
import jxl.Workbook;

/**
 *
 * @author USER
 */
public class P_Perceptron extends javax.swing.JPanel {

    /**
     * Creates new form P_Perceptron
     */
    private int s = 0, m = 0, h = 0;
        Toolkit toolkit;
    Timer timer;
  //  int cek[];
    
  //  int a;
    double mse;
    public P_Perceptron() {
        initComponents();
    //    a = 1;
        mse = 100;
    }
    
    int bipolar(double v, double t){
        int hasil = 2;
        if(v >= t ){
            hasil = 4;
        }
        return hasil;
    }
    
    int linear(double v, double t){
        int hasil = 0;
        if(v >= t ){
            hasil = 1;
        }
        return hasil;
    }
    
    String cek_bangkrut(double v, double t){
        String hasil = "Bangkrut";
        if(v >= t ){
            hasil = "Tidak Bangkrut";
        }
        return hasil;
    }
    
    int totalcek(int p[]){
        int jumlah = 0;
        for(int i=0;i<p.length;i++){
            jumlah = jumlah + p[i];
            
        }
        return jumlah;
    }
    
    class proses_iterasi extends TimerTask{
        int loop = 1;
        

        @Override
        public void run() {
            if (loop <= 1000) {
                if(mse <= Double.parseDouble(jTextField2.getText())){ 
                    toolkit.beep();
                    System.out.format("\nThat's it.. Done..!1");
                    stopwatch1.stop();
                    JOptionPane.showMessageDialog(
                            null,
            "Sudah dapat mengenali dengan benar semua vektor yang dilatihkan", "Information",
            JOptionPane.QUESTION_MESSAGE);
                    timer.cancel();
                
                }else{
                    jButton7ActionPerformed(null);
                iterasi.setText(Integer.toString(loop));
                
                }
                loop++;
                
            }else{
                toolkit.beep();
                System.out.format("\nThat's it.. Done..!1");
                timer.cancel();
            }
            
            
        }
        
    }
    public void aksi_iterasi(){
        toolkit = Toolkit.getDefaultToolkit();
        timer = new java.util.Timer();
        timer.schedule(new proses_iterasi(), 0, // initial delay
                1 * 1000); // subsequent rate
        stopwatch1.start();
    }
//    private void sukses(){
//        JOptionPane.showMessageDialog(
//            perceptron_linear.this,
//            "Sample info message", "Sample title",
//            JOptionPane.INFORMATION_MESSAGE);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_w1 = new javax.swing.JTextField();
        tf_w2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_b = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_laju = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_t = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        iterasi = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        tf_w3 = new javax.swing.JTextField();
        tf_w4 = new javax.swing.JTextField();
        tf_w5 = new javax.swing.JTextField();
        tf_w6 = new javax.swing.JTextField();
        tf_w7 = new javax.swing.JTextField();
        tf_w8 = new javax.swing.JTextField();
        tf_w9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        stopwatch1 = new ann.stopwatch();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();

        jLabel1.setText("w =[");

        tf_w1.setText("0.9");

        tf_w2.setText("-0.8");

        jLabel2.setText("]");

        jLabel3.setText("b =");

        tf_b.setText("2");

        jLabel4.setText("Laju pembelajaran =");

        tf_laju.setText("0.8");

        jLabel5.setText("T =");

        tf_t.setText("2");

        jButton7.setText("Proses");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "5", "1", "1", "1", "2", "1", "3", "1", "1", "2"},
                {"2", "5", "4", "4", "5", "7", "10", "3", "2", "1", "2"},
                {"3", "8", "10", "10", "8", "7", "10", "9", "7", "1", "4"},
                {"4", "8", "7", "5", "10", "7", "9", "5", "5", "4", "4"},
                {"5", "8", "7", "5", "10", "7", "9", "5", "5", "4", "4"},
                {"6", "4", "1", "1", "1", "2", "1", "2", "1", "1", "2"},
                {"7", "5", "3", "3", "3", "2", "3", "4", "4", "1", "4"},
                {"8", "1", "1", "1", "1", "2", "1", "3", "1", "1", "2"},
                {"9", "5", "2", "3", "4", "2", "7", "3", "6", "1", "4"},
                {"10", "3", "2", "1", "1", "1", "1", "2", "1", "1", "2"},
                {"11", "5", "1", "1", "1", "2", "1", "2", "1", "1", "2"},
                {"12", "10", "7", "7", "3", "8", "5", "7", "4", "3", "4"},
                {"13", "2", "1", "1", "2", "2", "1", "3", "1", "1", "2"},
                {"14", "10", "10", "10", "8", "6", "1", "8", "9", "1", "4"},
                {"15", "5", "4", "4", "9", "2", "10", "5", "6", "1", "4"},
                {"16", "6", "10", "10", "2", "8", "10", "7", "3", "3", "4"},
                {"17", "10", "10", "10", "4", "8", "1", "8", "10", "1", "4"},
                {"18", "1", "1", "1", "1", "2", "1", "2", "1", "2", "2"},
                {"19", "4", "1", "1", "3", "2", "1", "3", "1", "1", "2"},
                {"20", "7", "8", "7", "2", "4", "8", "3", "8", "2", "4"}
            },
            new String [] {
                "N", "Clump Thickness", "Uniformity of Cell Size", "Uniformity of Cell Shape", "Marginal Adhesion", "Single Epithelial Cell Size", "Bare Nuclei", "Bland Chromatin", "Normal Nucleoli", "Mitoses", "Class"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Automatic");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Iterasi ke = ");

        iterasi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        iterasi.setText("0 ");

        jLabel7.setText("Soal :");

        jButton3.setText("Proses");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tf_w3.setText("-0.8");

        tf_w4.setText("-0.8");

        tf_w5.setText("-0.8");

        tf_w6.setText("-0.8");

        tf_w7.setText("-0.8");

        tf_w8.setText("-0.8");

        tf_w9.setText("-0.8");

        jLabel11.setText("Set Jumlah Row =");

        jTextField1.setText("0");

        jButton4.setText("Set");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Open File...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel12.setText("MSE =");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N", "Clump Thickness", "Uniformity of Cell Size", "Uniformity of Cell Shape", "Marginal Adhesion", "Single Epithelial Cell Size", "Bare Nuclei", "Bland Chromatin", "Normal Nucleoli", "Mitoses", "Class", "Prediksi"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton6.setText("Open File...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel13.setText("Set Jumlah Row =");

        jButton8.setText("Set");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTextField3.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_laju, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_t, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iterasi)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_b))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stopwatch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_w1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_w2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_w3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_w4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_w5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(tf_w6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_w7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_w8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_w9, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tf_w1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_w2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(tf_w3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_w4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_w5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_w6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_w7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_w8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_w9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tf_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(tf_laju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(tf_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(stopwatch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7)
                        .addComponent(jButton2)
                        .addComponent(jLabel6)
                        .addComponent(iterasi))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jButton4)
                        .addComponent(jButton5)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jLabel7)
                    .addComponent(jButton3)
                    .addComponent(jLabel13)
                    .addComponent(jButton8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
        int cek[]
                = new int[jTable1.getRowCount()];
        double w1 = Double.parseDouble(tf_w1.getText());
        double w2 = Double.parseDouble(tf_w2.getText());
        double w3 = Double.parseDouble(tf_w3.getText());
        double w4 = Double.parseDouble(tf_w4.getText());
        double w5 = Double.parseDouble(tf_w5.getText());
        double w6 = Double.parseDouble(tf_w6.getText());
        double w7 = Double.parseDouble(tf_w7.getText());
        double w8 = Double.parseDouble(tf_w8.getText());
        double w9 = Double.parseDouble(tf_w9.getText());

        double b = Double.parseDouble(tf_b.getText());
        double t = Double.parseDouble(tf_t.getText());

        double laju = Double.parseDouble(tf_laju.getText());
        DecimalFormat dd = new DecimalFormat("#.##");
        for(int i=0;i<jTable1.getRowCount();i++){
            double x1 = Double.parseDouble(jTable1.getValueAt(i, 1).toString());
            double x2 = Double.parseDouble(jTable1.getValueAt(i, 2).toString());
            double x3 = Double.parseDouble(jTable1.getValueAt(i, 3).toString());
            double x4 = Double.parseDouble(jTable1.getValueAt(i, 4).toString());
            double x5 = Double.parseDouble(jTable1.getValueAt(i, 5).toString());
            double x6 = Double.parseDouble(jTable1.getValueAt(i, 6).toString());
            double x7 = Double.parseDouble(jTable1.getValueAt(i, 7).toString());
            double x8 = Double.parseDouble(jTable1.getValueAt(i, 8).toString());
            double x9 = Double.parseDouble(jTable1.getValueAt(i, 9).toString());

            double d = Double.parseDouble(jTable1.getValueAt(i, 10).toString());

            double v = ((x1*w1)+(x2*w2)+(x3*w3)+(x4*w4)+(x5*w5)+(x6*w6)+(x7*w7)+(x8*w8)+(x9*w9))+b;
            int y = bipolar(v, t);

            if(d != y){
                double delta_w = laju * (d-y);
                double delta_w1 = delta_w * x1;
                double delta_w2 = delta_w * x2;
                double delta_w3 = delta_w * x3;
                double delta_w4 = delta_w * x4;
                double delta_w5 = delta_w * x5;
                double delta_w6 = delta_w * x6;
                double delta_w7 = delta_w * x7;
                double delta_w8 = delta_w * x8;
                double delta_w9 = delta_w * x9;

                w1 = w1 + delta_w1;
                w2 = w2 + delta_w2;
                w3 = w3 + delta_w3;
                w4 = w4 + delta_w4;
                w5 = w5 + delta_w5;
                w6 = w6 + delta_w6;
                w7 = w7 + delta_w7;
                w8 = w8 + delta_w8;
                w9 = w9 + delta_w9;

                b = b + laju * (d-y);
                cek[i] = 1;
            }else{
                cek[i] = 0;
            }
            tf_w1.setText(dd.format(w1));
            tf_w2.setText(dd.format(w2));
            tf_w3.setText(dd.format(w3));
            tf_w4.setText(dd.format(w4));
            tf_w5.setText(dd.format(w5));
            tf_w6.setText(dd.format(w6));
            tf_w7.setText(dd.format(w7));
            tf_w8.setText(dd.format(w8));
            tf_w9.setText(dd.format(w9));

            tf_b.setText(dd.format(b));
        }

        int a = totalcek(cek);
        double as = a;
        double rowcount =jTable1.getRowCount(); 
        double aku = as / rowcount;
        mse = aku;
            System.out.println(aku+" = "+jTable1.getRowCount()+" * "+a);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        aksi_iterasi();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        double t = Double.parseDouble(tf_t.getText());
        double w1 = Double.parseDouble(tf_w1.getText());
        double w2 = Double.parseDouble(tf_w2.getText());
        double w3 = Double.parseDouble(tf_w3.getText());
        double w4 = Double.parseDouble(tf_w4.getText());
        double w5 = Double.parseDouble(tf_w5.getText());
        double w6 = Double.parseDouble(tf_w6.getText());
        double w7 = Double.parseDouble(tf_w7.getText());
        double w8 = Double.parseDouble(tf_w8.getText());
        double w9 = Double.parseDouble(tf_w9.getText());

        double b = Double.parseDouble(tf_b.getText());

        for (int i = 0; i < jTable2.getRowCount(); i++) {
            double x1 = Double.parseDouble(jTable2.getValueAt(i, 1).toString());
            double x2 = Double.parseDouble(jTable2.getValueAt(i, 2).toString());
            double x3 = Double.parseDouble(jTable2.getValueAt(i, 3).toString());
            double x4 = Double.parseDouble(jTable2.getValueAt(i, 4).toString());
            double x5 = Double.parseDouble(jTable2.getValueAt(i, 5).toString());
            double x6 = Double.parseDouble(jTable2.getValueAt(i, 6).toString());
            double x7 = Double.parseDouble(jTable2.getValueAt(i, 7).toString());
            double x8 = Double.parseDouble(jTable2.getValueAt(i, 8).toString());
            double x9 = Double.parseDouble(jTable2.getValueAt(i, 9).toString());
            
            double v = ((x1*w1)+(x2*w2)+(x3*w3)+(x4*w4)+(x5*w5)+(x6*w6)+(x7*w7)+(x8*w8)+(x9*w9))+b;
            int y = bipolar(v, t);
            jTable2.setValueAt(y, i, 11);
        }
     /*   double x1 = Double.parseDouble(tf_soal1.getText());
        double x2 = Double.parseDouble(tf_soal2.getText());
        double x3 = Double.parseDouble(tf_soal3.getText());
        double x4 = Double.parseDouble(tf_soal4.getText());
        double x5 = Double.parseDouble(tf_soal5.getText());
        double x6 = Double.parseDouble(tf_soal6.getText());
        double x7 = Double.parseDouble(tf_soal7.getText());
        double x8 = Double.parseDouble(tf_soal8.getText());
        double x9 = Double.parseDouble(tf_soal9.getText());

        double v = ((x1*w1)+(x2*w2)+(x3*w3)+(x4*w4)+(x5*w5)+(x6*w6)+(x7*w7)+(x8*w8)+(x9*w9))+b;
        int y = bipolar(v, t);
        hasil.setText(Integer.toString(y));*/
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setttable(jTable1, Integer.parseInt(jTextField1.getText()));
        for (int i = 0; i < Integer.parseInt(jTextField1.getText()); i++) {
            jTable1.setValueAt(i+1, i, 0);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Excel File", "xls"));

        int retval = chooser.showOpenDialog(null);
        if(retval == JFileChooser.APPROVE_OPTION){
            File f = chooser.getSelectedFile();
            filltable(f,jTable1);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Excel File", "xls"));

        int retval = chooser.showOpenDialog(null);
        if(retval == JFileChooser.APPROVE_OPTION){
            File f = chooser.getSelectedFile();
            filltable1(f,jTable2);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        setttable2(jTable2, Integer.parseInt(jTextField3.getText()));
        for (int i = 0; i < Integer.parseInt(jTextField3.getText()); i++) {
            jTable2.setValueAt(i+1, i, 0);
        }
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iterasi;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private ann.stopwatch stopwatch1;
    private javax.swing.JTextField tf_b;
    private javax.swing.JTextField tf_laju;
    private javax.swing.JTextField tf_t;
    private javax.swing.JTextField tf_w1;
    private javax.swing.JTextField tf_w2;
    private javax.swing.JTextField tf_w3;
    private javax.swing.JTextField tf_w4;
    private javax.swing.JTextField tf_w5;
    private javax.swing.JTextField tf_w6;
    private javax.swing.JTextField tf_w7;
    private javax.swing.JTextField tf_w8;
    private javax.swing.JTextField tf_w9;
    // End of variables declaration//GEN-END:variables

    public void setttable(JTable table, int row){
            DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(    
              new Object [][] {
                    {null,null,null,null,null,null,null,null,null,null,null}
                },
                new String [] {
                    "No","Clump Thickness","Uniformity of Cell Size", "Uniformity of Cell Shape",
                    "Marginal Adhesion","Single Epithelial Cell Size","Bare Nuclei","Bland Chromatin","Normal Nucleoli",
                    "Mitoses","Class"
                }  
        );

        table.setModel(tableModel);
            String[] data= {null,null,null,null,null,null,null,null,null,null,null};

            for (int i=1; i<row; i++){
                ((DefaultTableModel)table.getModel()).addRow(data);
            }
     }
    
    public void setttable2(JTable table, int row){
            DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(    
              new Object [][] {
                    {null,null,null,null,null,null,null,null,null,null,null,null}
                },
                new String [] {
                    "No","Clump Thickness","Uniformity of Cell Size", "Uniformity of Cell Shape",
                    "Marginal Adhesion","Single Epithelial Cell Size","Bare Nuclei","Bland Chromatin","Normal Nucleoli",
                    "Mitoses","Class","Prediksi"
                }  
        );

        table.setModel(tableModel);
            String[] data= {null,null,null,null,null,null,null,null,null,null,null,null};

            for (int i=1; i<row; i++){
                ((DefaultTableModel)table.getModel()).addRow(data);
            }
     }

    private void filltable(File excelfile, JTable table) {
        if(excelfile.exists()){
            try {
                Workbook workbook = Workbook.getWorkbook(excelfile);
                Sheet sheet = workbook.getSheet(0);
                //int jumlahrow = sheet.getRows();
                //int jumlahcolumn = sheet.getColumns();
                //untuk setting table
                
                for (int row = 0; row < table.getRowCount(); row++) {
                    for (int column = 1; column < table.getColumnCount(); column++) {
                        String isi = sheet.getCell(column-1, row).getContents();
                        table.setValueAt(isi, row, column);
                    }
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }
    
    private void filltable1(File excelfile, JTable table) {
        if(excelfile.exists()){
            try {
                Workbook workbook = Workbook.getWorkbook(excelfile);
                Sheet sheet = workbook.getSheet(0);
                //int jumlahrow = sheet.getRows();
                //int jumlahcolumn = sheet.getColumns();
                //untuk setting table
                
                for (int row = 0; row < table.getRowCount(); row++) {
                    for (int column = 1; column < table.getColumnCount()-1; column++) {
                        String isi = sheet.getCell(column-1, row).getContents();
                        table.setValueAt(isi, row, column);
                    }
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

}
