/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ann;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author USER
 */
public class stopwatch extends javax.swing.JPanel {
private int s = 0, m = 0, h = 0;
    /**
     * Creates new form stopwatch
     */
Timer timer;
    public stopwatch() {
        initComponents();
        //ActionListener al = new ActionListener() {
          //  public void actionPerformed(ActionEvent ae) {setDuration();}
        //};
       // new Timer(10, al).start();
    }
    
    public void start(){
        ActionListener al = new ActionListener() {
            public void actionPerformed(ActionEvent ae) {setDuration();}
        };
        timer = new Timer(10, al);
        timer.start();
    }
    
    public void stop(){
        timer.stop();
        
    }
    
    public void setDuration(){
        //menghitung selisih waktu start dengan waktu sekarang
        if(s==60){
            s = 0;
            m++;
        }else s++;
        if(m==60){
            m = 0;
            h++;
        }
        Time t = new Time();
        TimeEntity te = t.timeFormat(s, m, h);
        lblStopWatch.setText(te.getJam()+" : "+te.getMenit()+" : "+te.getDetik());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStopWatch = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lblStopWatch.setText("00 : 00 : 00");

        jLabel1.setText("Waktu :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStopWatch)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStopWatch)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblStopWatch;
    // End of variables declaration//GEN-END:variables
}
